### ISSUE TITLE
Has Some MVP demo ? 

### ISSUE THREAD

**Issue by lmj01** [DunkleMango/GLRF#10]
I like this repo code, it's clean and beautiful!

I inherit GLRF::App, and run on the AppFrame, but after compile the code, nothing is show!

I view code, glfw create window inside, why it not show the window with title ? I missing something or i must fill some code in App instance object.

**Comment by lmj01** [comment]
I got the problem, As in Mouse::Mouse constructor, has the Mouse constructor, and de-constructor immediately, 
this ~Mouse function occur problem.
I test debug on Window 10

**Comment by DunkleMango** [comment]
Hey there!

I'm glad that you like the style of my framework. It has become a bit dusty after the years, but I think I can help you out.

I made a few changes to an old example application, that I created to test the framework, and made it public. You can find it here: https://github.com/DunkleMango/GLRF_Example

I think it's easier to just look at some already implemented functionality and find what you need. The example has all the basic things that one might need. Here is a screenshot of what it can do.

![Image of what the application can do](https://github.com/DunkleMango/GLRF/assets/44678770/bdd372ca-963a-4ab6-b515-2eae09d90df9)

You can look for textures on this site, if you want: https://ambientcg.com/
But you probably have to change the names to better reflect the material properties for the loader.

If you require more specific help, feel free to ask.
